# Generated by Django 3.2.5 on 2021-07-10 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=40)),
                ('content', models.TextField()),
                ('author', models.EmailField(max_length=40)),
                ('timeStamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
